# Generated by Django 3.0.7 on 2020-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('n_places', models.IntegerField()),
                ('form', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('date_reserved', models.DateField(blank=True, null=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
