# Generated by Django 3.0.7 on 2020-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='table',
            name='size',
        ),
        migrations.AddField(
            model_name='table',
            name='coordinates_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='coordinates_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='size_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='size_w',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
